version: '3.4'
services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - '${APP_PORT}:80'
    env_file:
      - ./.env
