[build]
  command = "npm install --include=optional --loglevel verbose || (echo '---- NPM DEBUG LOG ----' && ls -lah /opt/buildhome/.npm/_logs && tail -n 200 /opt/buildhome/.npm/_logs/*debug-0.log && exit 1) ; npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"