[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "23"

[build.lifecycle]
  install = "npm install --include=optional --loglevel verbose || (echo '---- NPM DEBUG LOG (full) ----' && cat /opt/buildhome/.npm/_logs/*debug-0.log && exit 1)"